wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 10
lr:
  value: 0.0001
n_hidden:
  value: 3
n_hidden_units:
  value: 128
optim_algo:
  value: nesterov
weight_decay:
  value: 0
weight_init:
  value: random
