wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 5
lr:
  value: 0.001
n_hidden:
  value: 3
n_hidden_units:
  value: 32
optim_algo:
  value: adam
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
