wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 5
lr:
  value: 0.001
n_hidden:
  value: 3
n_hidden_units:
  value: 64
optim_algo:
  value: nadam
weight_decay:
  value: 0.5
weight_init:
  value: xavier
