_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.10
            "5": 0.19.8
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": linux-x86_64
activation:
    value: tanh
batch_size:
    value: 32
epochs:
    value: 5
lr:
    value: 0.0001
n_hidden:
    value: 5
n_hidden_units:
    value: 128
optim_algo:
    value: sgd
