wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 10
l2_coeff:
  value: 0
learning_rate:
  value: 0.001
loss_func:
  value: cross_ent
n_hidden:
  value: 4
n_hidden_units:
  value: 128
optim_algo:
  value: adam
weights_init:
  value: xavier_uniform
