wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 10
l2_coeff:
  value: 0.5
learning_rate:
  value: 0.001
loss_func:
  value: mse
n_hidden:
  value: 4
n_hidden_units:
  value: 64
optim_algo:
  value: adam
weights_init:
  value: random
