wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 5
l2_coeff:
  value: 0.5
learning_rate:
  value: 0.001
loss_func:
  value: mse
n_hidden:
  value: 4
n_hidden_units:
  value: 128
optim_algo:
  value: nag
weights_init:
  value: random
