wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 5
l2_coeff:
  value: 0.5
learning_rate:
  value: 0.0001
loss_func:
  value: cross_ent
n_hidden:
  value: 5
n_hidden_units:
  value: 32
optim_algo:
  value: adam
weights_init:
  value: xavier_uniform
