wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 5
l2_coeff:
  value: 0.0005
learning_rate:
  value: 0.0001
loss_func:
  value: mse
n_hidden:
  value: 3
n_hidden_units:
  value: 32
optim_algo:
  value: sgdm
weights_init:
  value: random
