wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 10
lr:
  value: 0.001
n_hidden:
  value: 3
n_hidden_units:
  value: 64
optim_algo:
  value: nadam
weight_decay:
  value: 0.0005
weight_init:
  value: random
