wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 10
lr:
  value: 0.001
n_hidden:
  value: 3
n_hidden_units:
  value: 64
optim_algo:
  value: sgd
weight_decay:
  value: 0.5
weight_init:
  value: xavier
