_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.10
            "5": 0.19.8
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": linux-x86_64
activation:
    value: sigmoid
batch_size:
    value: 32
epochs:
    value: 10
hidden_layers:
    value:
        - 128
        - 128
learning_rate:
    value: 0.0001
