_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.10.10
            "5": 0.19.8
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": linux-x86_64
activation:
    value: sigmoid
batch_size:
    value: 64
epochs:
    value: 10
lr:
    value: 0.0001
n_hidden:
    value: 4
n_hidden_units:
    value: 128
optim_algo:
    value: nesterov
weight_decay:
    value: 0.0005
weight_init:
    value: xavier
