wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 10
lr:
  value: 0.001
n_hidden:
  value: 3
n_hidden_units:
  value: 128
optim_algo:
  value: rmsprop
weight_decay:
  value: 0.5
weight_init:
  value: random
