wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 5
lr:
  value: 0.001
n_hidden:
  value: 5
n_hidden_units:
  value: 128
optim_algo:
  value: nesterov
weight_decay:
  value: 0
weight_init:
  value: random
