wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 5
l2_coeff:
  value: 0.5
learning_rate:
  value: 0.001
loss_func:
  value: mse
n_hidden:
  value: 5
n_hidden_units:
  value: 64
optim_algo:
  value: sgdm
weights_init:
  value: random
