_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.10
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
activation:
    value: sigmoid
batch_size:
    value: 32
beta:
    value: 0.999
beta1:
    value: 0.9
beta2:
    value: 0.999
dataset:
    value: fashion_mnist
epochs:
    value: 10
epsilon:
    value: 1e-08
hidden_size:
    value: 128
learning_rate:
    value: 0.001
loss:
    value: mse
momentum:
    value: 0.9
num_layers:
    value: 5
optimizer:
    value: nadam
wandb_entity:
    value: da24s008-indian-institute-of-technology-madras
wandb_project:
    value: DA24S008_Assignment_1
weight_decay:
    value: 0
weight_init:
    value: xavier
