wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 5
lr:
  value: 0.0001
n_hidden:
  value: 5
n_hidden_units:
  value: 32
optim_algo:
  value: rmsprop
weight_decay:
  value: 0
weight_init:
  value: xavier
