wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 5
lr:
  value: 0.001
n_hidden:
  value: 3
n_hidden_units:
  value: 32
optim_algo:
  value: nesterov
weight_decay:
  value: 0
weight_init:
  value: random
