wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 5
l2_coeff:
  value: 0.0005
loss_func:
  value: mse
lr:
  value: 0.0001
n_hidden:
  value: 5
n_hidden_units:
  value: 128
optim_algo:
  value: nag
weights_init:
  value: random
