_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 14
                - 23
                - 24
                - 55
            "4": 3.10.10
            "5": 0.19.8
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": linux-x86_64
activation:
    value: relu
batch_size:
    value: 32
epochs:
    value: 5
l2_coeff:
    value: 0.5
learning_rate:
    value: 0.001
loss_func:
    value: mse
n_hidden:
    value: 3
n_hidden_units:
    value: 64
optim_algo:
    value: nag
weights_init:
    value: xavier_uniform
